language: generic
sudo: false

matrix:
  include:
    - os: linux
      env: CXX=g++-5 BUILDTYPE=Release
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-5' ]
    - os: linux
      env: CXX=clang++ BUILDTYPE=Release MASON_CLANG=true
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6','libstdc++-5-dev' ]
    - os: linux
      env: CXX=clang++ BUILDTYPE=Debug MASON_CLANG=true
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6','libstdc++-5-dev' ]
    - os: osx
      osx_image: xcode7.3

cache: apt

before_install:
 - source ./travis_setup.sh

script:
 - |
   if [[ ${BUILDTYPE} == 'Debug' ]]; then
     make debug
   else
     make test
   fi
